#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/dist/WatermarkFlow.app"
EXPECTED_VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
EXPECTED_BUILD="$(tr -d '[:space:]' < "$ROOT/BUILD_NUMBER")"

cd "$ROOT"
swift run WatermarkFlowTests
"$ROOT/scripts/build-app.sh"
SELF_TEST_OUTPUT="$("$APP/Contents/MacOS/WatermarkFlow" --self-test)"
echo "$SELF_TEST_OUTPUT"

VERSION="$(plutil -extract CFBundleShortVersionString raw "$APP/Contents/Info.plist")"
AUTHOR="$(plutil -extract Author raw "$APP/Contents/Info.plist")"
AUTHOR_URL="$(plutil -extract AuthorURL raw "$APP/Contents/Info.plist")"
WEBSITE="$(plutil -extract Website raw "$APP/Contents/Info.plist")"
BUILD="$(plutil -extract CFBundleVersion raw "$APP/Contents/Info.plist")"
ARCHITECTURES="$(lipo -archs "$APP/Contents/MacOS/WatermarkFlow")"
codesign --verify --deep --strict "$APP"

test "$VERSION" = "$EXPECTED_VERSION"
test "$AUTHOR" = "X @wlzh"
test "$AUTHOR_URL" = "https://x.com/wlzh"
test "$WEBSITE" = "https://869hr.uk"
test "$BUILD" = "$EXPECTED_BUILD"
test "$ARCHITECTURES" = "x86_64 arm64" -o "$ARCHITECTURES" = "arm64 x86_64"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_VERSION=$EXPECTED_VERSION"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_BUILD=$EXPECTED_BUILD"
grep -Fq "## [$EXPECTED_VERSION]" "$ROOT/CHANGELOG.md"
grep -Fq "v$EXPECTED_VERSION PRD" "$ROOT/README.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/prd.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/design.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/dev.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/plan.md"
test -f "$ROOT/docs/testing/v$EXPECTED_VERSION-test-report.md"

echo "TEST_ALL=PASS"
echo "VERIFIED_VERSION=$VERSION"
echo "VERIFIED_AUTHOR=$AUTHOR"
echo "VERIFIED_AUTHOR_URL=$AUTHOR_URL"
echo "VERIFIED_WEBSITE=$WEBSITE"
echo "VERIFIED_BUILD=$BUILD"
echo "VERIFIED_ARCHITECTURES=$ARCHITECTURES"
echo "VERIFIED_RELEASE_DOCUMENTS=v$EXPECTED_VERSION"
