#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/dist/WatermarkFlow.app"
EXPECTED_VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
EXPECTED_BUILD="$(tr -d '[:space:]' < "$ROOT/BUILD_NUMBER")"

cd "$ROOT"
swift run WatermarkFlowTests
"$ROOT/scripts/build-app.sh"
SELF_TEST_OUTPUT="$("$APP/Contents/MacOS/WatermarkFlow" --self-test)"
echo "$SELF_TEST_OUTPUT"

VERSION="$(plutil -extract CFBundleShortVersionString raw "$APP/Contents/Info.plist")"
AUTHOR="$(plutil -extract Author raw "$APP/Contents/Info.plist")"
AUTHOR_URL="$(plutil -extract AuthorURL raw "$APP/Contents/Info.plist")"
WEBSITE="$(plutil -extract Website raw "$APP/Contents/Info.plist")"
LICENSE="$(plutil -extract License raw "$APP/Contents/Info.plist")"
BUILD="$(plutil -extract CFBundleVersion raw "$APP/Contents/Info.plist")"
ARCHITECTURES="$(lipo -archs "$APP/Contents/MacOS/WatermarkFlow")"
codesign --verify --deep --strict "$APP"

test "$VERSION" = "$EXPECTED_VERSION"
test "$AUTHOR" = "X @wlzh"
test "$AUTHOR_URL" = "https://x.com/wlzh"
test "$WEBSITE" = "https://869hr.uk"
test "$LICENSE" = "MIT"
test "$BUILD" = "$EXPECTED_BUILD"
test "$ARCHITECTURES" = "x86_64 arm64" -o "$ARCHITECTURES" = "arm64 x86_64"
test -f "$APP/Contents/Resources/LICENSE.txt"
cmp -s "$ROOT/LICENSE" "$APP/Contents/Resources/LICENSE.txt"
grep -Fxq "MIT License" "$ROOT/LICENSE"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_VERSION=$EXPECTED_VERSION"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_BUILD=$EXPECTED_BUILD"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_REMOVE_RESTORE_WATERMARK=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_TEMPLATE_REPLACEMENT=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_CANVAS_ZOOM=PASS range=25%-1000%"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_TILED_LAYOUT=PASS density=8"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_DUAL_LAYOUT_SETTINGS=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_DUAL_LAYOUT_CONTRAST=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_ADAPTIVE_CONTRAST=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_CUSTOM_LOGO_TEXT_TEMPLATE=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_CUSTOM_TEMPLATE_SOURCE_ISOLATION=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_CUSTOM_TEMPLATE_COPY=PASS"
echo "$SELF_TEST_OUTPUT" | grep -Fq "SELF_TEST_DEFAULT_TEMPLATE=PASS value="
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_CLIPBOARD_AUTOLOAD=PASS modes=empty,pending,always,off,non-image"
echo "$SELF_TEST_OUTPUT" | grep -Fxq "SELF_TEST_CLIPBOARD_SELF_WRITE_SUPPRESSION=PASS"
grep -Fq "## [$EXPECTED_VERSION]" "$ROOT/CHANGELOG.md"
grep -Fq "v$EXPECTED_VERSION PRD" "$ROOT/README.md"
grep -Fq "快捷默认模板" "$ROOT/README.md"
grep -Fq "自动对比" "$ROOT/README.md"
grep -Fq "仅空画布自动载入" "$ROOT/docs/INSTALL.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/prd.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/design.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/dev.md"
test -f "$ROOT/docs/prd/v$EXPECTED_VERSION/plan.md"
test -f "$ROOT/docs/testing/v$EXPECTED_VERSION-test-report.md"

echo "TEST_ALL=PASS"
echo "VERIFIED_VERSION=$VERSION"
echo "VERIFIED_AUTHOR=$AUTHOR"
echo "VERIFIED_AUTHOR_URL=$AUTHOR_URL"
echo "VERIFIED_WEBSITE=$WEBSITE"
echo "VERIFIED_LICENSE=$LICENSE"
echo "VERIFIED_BUILD=$BUILD"
echo "VERIFIED_ARCHITECTURES=$ARCHITECTURES"
echo "VERIFIED_RELEASE_DOCUMENTS=v$EXPECTED_VERSION"
